vti_encoding:SR|utf8-nl
vti_author:SR|BEAST\\Jake
vti_modifiedby:SR|BEAST\\Jake
vti_timelastmodified:TR|15 Apr 2001 05:07:58 -0000
vti_timecreated:TR|13 Apr 2001 21:01:03 -0000
vti_lineageid:SR|{785D35A7-2A96-438D-A1F1-835B3423D52E}
vti_extenderversion:SR|5.0.2.2623
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TR|13 Apr 2001 21:01:17 -0000
vti_cacheddtm:TX|13 Apr 2001 21:01:03 -0000
vti_filesize:IR|27559
